version: '3.8'

services:
  frontend:
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=your_database_url_here
      - OTHER_ENV_VAR=your_value_here

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend